### PR TITLE
Update protobuf dep to 23.1.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`MODULE.bazel` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4#-NoSGhn61mRl-3qr7dYW:-NoSGhn61mRl-3qr7dYX:be2rzwa) ([raw file](https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/blob/4623e5c2243d6be3cb7c029cefe69c9d3e69deac/MODULE.bazel#L22)):*
> ```Starlark
> bazel_dep(
>     name = "rules_proto",
>     version = "6.0.0-rc1",
> ```

whats the reason for adopting a release candidate here?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`MODULE.bazel` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4#-NoSGhn61mRl-3qr7dYW:-NoSIVCv74BGlfi078Kp:b-h88sos) ([raw file](https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/blob/4623e5c2243d6be3cb7c029cefe69c9d3e69deac/MODULE.bazel#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the reason for adopting a release candidate here?
</blockquote></details>

The latest official release is specifically tied to protobuf 21.7. The RC is known to be compatible with 23.1.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`MODULE.bazel` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4#-NoSGhn61mRl-3qr7dYW:-NoXpJvC8dLvKuPNfTA_:bmuzo32) ([raw file](https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/blob/ac8783135643d6abc2edbd5971aeaab3fa2bec02/MODULE.bazel#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The latest official release is specifically tied to protobuf 21.7. The RC is known to be compatible with 23.1.
</blockquote></details>

I'd prefer to be on 21.7 then until its not a rc unless we have a strong reason.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`MODULE.bazel` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4#-NoSGhn61mRl-3qr7dYW:-NoXvRj-81sVPxFTFFel:b-4pak95) ([raw file](https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/blob/ac8783135643d6abc2edbd5971aeaab3fa2bec02/MODULE.bazel#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer to be on 21.7 then until its not a rc unless we have a strong reason.
</blockquote></details>

We do. This is blocking upgrading gRPC and therefore adding Python gRPC support for planning. 21.7 is also ancient, released Sept of 2022. Even 23.1 is pretty old at May 2023 given that the latest is 25.2 released last week. 23.1 is the latest that's been published to the Bazel Central Registry, and therefore the latest that is known to work for rules_proto which already migrated.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`MODULE.bazel` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4#-NoSGhn61mRl-3qr7dYW:-NoY3veSB4N-X7YioH4G:bc4otlj) ([raw file](https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/blob/ac8783135643d6abc2edbd5971aeaab3fa2bec02/MODULE.bazel#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We do. This is blocking upgrading gRPC and therefore adding Python gRPC support for planning. 21.7 is also ancient, released Sept of 2022. Even 23.1 is pretty old at May 2023 given that the latest is 25.2 released last week. 23.1 is the latest that's been published to the Bazel Central Registry, and therefore the latest that is known to work for rules_proto which already migrated.
</blockquote></details>

See https://github.com/bazelbuild/rules_proto/issues/178

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_kotlin_jvm/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
